{ pkgs, inputs, system, sys, ... }: {
home.packages = 
(with pkgs; [
		gnome-graphs
		aonsoku
		(ghc.withPackages (ps:
			with ps; [ vector containers lens aeson split ]
		))
		haskell-language-server
		cabal-install
		lrcget
		kanshi
		localsend
		rlci
		libqalculate
		(pkgs.callPackage ./wm/waybar/wf-recorder.nix {})
		inputs.iio-sway.packages.${system}.default
		inputs.hexecute.packages.${system}.default
		moonlight-qt
		mods
		way-displays
		cbonsai
		libnotify
		wdisplays
		nixos-shell
		gtk4
		binwalk
		koreader
		wireshark
		testdisk
		multiplex
		audacity
		inputs.nvim.packages.${pkgs.stdenv.hostPlatform.system}.default
		mpc
		heroic
		telegram-desktop
		sshfs
		apostrophe
		easyeffects
		inputs.firefox.packages.${system}.firefox-nightly-bin
# inputs.fmm.packages.${system}.default
		gamescope
		nicotine-plus
		fretboard
		haskellPackages.pointfree
		tree-sitter
		(import inputs.master { inherit system; }).ollama
		marksman
		codeberg-cli
		inputs.pabc-nix.packages.${pkgs.stdenv.hostPlatform.system}.default
		codeblocks
		typst
		tinymist
		pandoc
		nodejs
		haskellPackages.hoogle
		arduino
		arduino-cli
		zig
		zls
		arduino-language-server
		cassette
		cool-retro-term
		tgpt
		neovide
		lutris
		deploy-rs
		openvpn3
		swayimg
		element-desktop
		obs-studio
		fasole
		wmctrl
		typescript
		musikcube
		mindustry-wayland
		ags
		wineWowPackages.full
		wails
		restish
		ffmpeg
		lazydocker
		mpv
		(import inputs.old { inherit system; } ).clang-tools
		gcc
		mpg123
		parted
		aalib
		exiftool
		fzf
		zoxide
		sshpass
		simplex-chat-desktop
		nchat
		ncdu
		openboard
		leetcode-cli
		speedcrunch
		nemo
		tor-browser
		neofetch
		inputs.freesm.packages.${pkgs.stdenv.hostPlatform.system}.default
		bc
		gimp
		openjdk17-bootstrap
		osu-lazer-bin
		alsa-utils
		toilet figlet
		cowsay
		glib
		wf-recorder
		translate-shell
		github-cli
		mono
		fswatch
		brightnessctl
		transmission_4
		chromium
		ventoy
		file
		ueberzug
		element
		viu
		pyright
		just
		tmux
		ripgrep
		git
		lazygit
		go
		bear
		vitetris
		tty-clock
		fpc
		tree
		btop
		cava
		showmethekey
		jq
		nixd
		pulseaudio
		grim
		slurp
		wl-clipboard cliphist
		waybar
		winetricks
		wireplumber
		libreoffice
		p7zip
		ldmtool
		python311Packages.pip
		timeshift
		sonic-pi
		slstatus
		zip
		unzip
		cmake
		pamixer
		gnupg
		pavucontrol
		xclip
		lldb
		lua-language-server
		tmux
		obsidian
		slurp
		eza
		python311
		gnumake
		nitch
		direnv
		cartridges
		tlrc
		]);
}
